server:
  port: 8091
  tomcat:
    uri-encoding: UTF-8

spring:
  config:
    activate:
      on-profile: "test"

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1
    username: ENC(PdKa/rkB2ufRp1NGXNhxXQ==)
    password: ENC(KH+89yWRp8K4R389dQ1IKSEpgJ+qlKbn)

  h2:
    console:
      enabled: true
      path: /h2-console

  sql:
    init:
      schema-locations: classpath:init-data/h2db/schema.sql
      data-locations: classpath:init-data/h2db/data.sql
      username: ENC(PdKa/rkB2ufRp1NGXNhxXQ==)
      password: ENC(KH+89yWRp8K4R389dQ1IKSEpgJ+qlKbn)
      mode: always
      encoding: UTF-8


