drop table if exists MEMBER;
drop table if exists BANK;
drop table if exists ACCOUNT;
drop table if exists TRANS;

/** 회원 정보 (MEMBER) **/
CREATE TABLE MEMBER (
    MEMBER_NO BIGINT NOT NULL AUTO_INCREMENT COMMENT '회원번호',
    MEMBER_NAME VARCHAR(50) NOT NULL COMMENT '회원이름',
    PHONE VARCHAR(11) NOT NULL COMMENT '휴대폰번호',
    EMAIL VARCHAR(50) NOT NULL COMMENT '이메일',
    CONSTRAINT MEMBER_PK PRIMARY KEY(MEMBER_NO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT '회원정보';

/** 은행 정보 (BANK) **/
CREATE TABLE BANK (
    BANK_CD VARCHAR(3) NOT NULL COMMENT '은행코드',
    BANK_NAME VARCHAR(50) NOT NULL COMMENT '은행명',
    CONSTRAINT BANK_PK PRIMARY KEY(BANK_CD)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT '은행정보';

/** 계좌 정보 (ACCOUNT) **/
CREATE TABLE ACCOUNT (
    MEMBER_NO BIGINT NOT NULL COMMENT '회원번호',
    ACCOUNT_NO VARCHAR(30) NOT NULL COMMENT '계좌번호',
    BANK_CD VARCHAR(3) NOT NULL COMMENT '은행코드',
    STATUS CHAR(1) DEFAULT '1' COMMENT '상태 (1:정상 9:정지 0:해지)',
    PIN VARCHAR(50) NOT NULL COMMENT '계좌 PIN',
    DEPOSIT INT DEFAULT 0 COMMENT '잔액',
    CREATE_DATE TIMESTAMP NOT NULL COMMENT '계좌개설일시',
    CONSTRAINT ACCOUNT_PK PRIMARY KEY(MEMBER_NO, ACCOUNT_NO, BANK_CD)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT '계좌정보';

/** 거래 정보 (TRANS) **/
CREATE TABLE TRANS (
    TRANS_ID VARCHAR(50) NOT NULL COMMENT '거래일련번호',
    TRANS_FG CHAR(1) NOT NULL COMMENT '거래구분 (1:입금, 2:출금, 3:이체)',
    TRANS_AMT INT NOT NULL COMMENT '거래금액',
    TRANS_DATE TIMESTAMP NOT NULL COMMENT '거래일시',
    MEMBER_NO BIGINT NOT NULL COMMENT '회원번호',
    ACCOUNT_NO VARCHAR(30) NOT NULL COMMENT '계좌번호',
    BANK_CD VARCHAR(3) NOT NULL COMMENT '은행코드',
    TRANS_TEXT VARCHAR(20) COMMENT '이체_받는 분 통장표시',
    TO_MEMBER_NO BIGINT COMMENT '이제_회원번호',
    TO_BANK_CD VARCHAR(3) COMMENT '이체_은행코드',
    TO_ACCOUNT_NO VARCHAR(30) COMMENT '이체_계좌번호',
    MEMO VARCHAR(30) COMMENT '메모',
    CONSTRAINT TRANS_PK PRIMARY KEY(TRANS_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT '거래정보';



/* 스키마 생성 */
CREATE SCHEMA STANDARD;

/* 시퀀스 생성 (거래일련번호) */
CREATE SEQUENCE STANDARD.TRANS_SEQ
START WITH 1
INCREMENT BY 1
MAXVALUE 999999
CYCLE;